# Generated by Django 3.0.4 on 2020-04-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=28, null=True, verbose_name='Имя Клиента'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_patronymic',
            field=models.CharField(blank=True, db_index=True, max_length=28, null=True, verbose_name='Отчество Клиента'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер Клиента'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_surname',
            field=models.CharField(blank=True, db_index=True, max_length=28, null=True, verbose_name='Фамилия Клиента'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uznali_o_nas',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Узнали о нас '),
        ),
    ]
