# Generated by Django 3.0.4 on 2020-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('order', '0002_auto_20200404_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='customer',
            field=models.ManyToManyField(blank=True, to='customer.Customer', verbose_name='Клиент'),
        ),
    ]
